name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:                                   #added
      run-job:
        description: "Run Specific Job"
        type: boolean
        required: false
      custom_message:
        description: "Enter a custom message"
        type: string
        required: true    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
      
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ github.event.inputs.custom_message }}"
      - name: Printing run-job boolean value
        if: ${{ inputs.run-job == true }}
        run: echo ${{ github.event.inputs.run-job }}







